# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20180708_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
